[workspace]
members = ["crates/*"]

[package]
name = "rue"
version = "0.1.0"
edition = "2021"

[dependencies]
clvmr = "0.3.0"
num-derive = "0.4.0"
num-traits = "0.2.15"
rowan = "0.15.11"
rue-lexer = { version = "0.1.0", path = "./crates/rue-lexer" }
rue-syntax = { version = "0.1.0", path = "./crates/rue-syntax" }