[package]
name = "rue-hir"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.0.1"
itertools = "0.11.0"
la-arena = "0.3.1"
num-bigint = "0.4.3"
rue-ast = { version = "0.1.0", path = "../rue-ast" }
rue-syntax = { version = "0.1.0", path = "../rue-syntax" }
