[package]
name = "rue-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clvmr = "0.3.0"
indexmap = "2.0.0"
num-bigint = "0.4.3"
rue-ast = { version = "0.1.0", path = "../rue-ast" }
rue-hir = { version = "0.1.0", path = "../rue-hir" }
