[package]
name = "rue-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clvmr = "0.3.0"
enum-as-inner = "0.6.0"
indexmap = "2.0.2"
itertools = "0.11.0"
la-arena = "0.3.1"
num-bigint = "0.4.3"
rowan = "0.15.13"
rue-ast = { path = "../rue-ast" }
rue-error = { path = "../rue-error" }
